name: Fedora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:42

    steps:
    - name: Install image dependencies
      run: |
        dnf install -y curl git gcovr 
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
        dnf install -y nodejs

    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive


    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: Build pages
      run: npm run script:build

    - name: install dependencies
      run: |
          dnf update -y
          dnf install -y \
            make \
            gcc \
            gcc-c++ \
            glibc-devel \
            gtk3-devel \
            webkit2gtk4.1-devel \
            gtk3 \
            webkit2gtk4.1 \
            pkgconf-pkg-config \
            boost-devel \
            boost-url \
            libnotify-devel

    - name: make
      run: make
      working-directory: ./engine

    - name: Generate installers
      run: npm run script:installers skip

