name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: Build pages
      run: npm run script:build

    - name: install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-3-0 \
            libwebkit2gtk-4.1-0 \
            pkg-config \
            libboost-all-dev \
            libnotify-dev

    - name: make
      run: make
      working-directory: ./engine

    - name: Generate installers
      run: npm run script:installers skip
